### ISSUE TITLE
'my-date-range-picker' is not a known element Error

### ISSUE THREAD

**Issue by imdivakar** [kekeh/mydaterangepicker#10]
hi @kekeh , I'm getting error after including "<my-date-range-picker></my-date-range-picker>" to my html.
Error:
'my-date-range-picker' is not a known element:
1. If 'my-date-range-picker' is an Angular component, then verify that it is part of this module.
2. If 'my-date-range-picker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Comment by kekeh** [comment]
I think you have to add **MyDateRangePickerModule** to the **NgModule** of your own application. 

At first update the date range picker to latest version **1.2.0**. Then follow instruction from here: https://github.com/kekeh/mydaterangepicker/blob/master/README.md

Here is also example: https://github.com/kekeh/mydaterangepicker/tree/master/sampleapp

**Comment by imdivakar** [comment]
@kekeh ya i followed the same step from this README file [https://github.com/kekeh/mydaterangepicker/blob/master/README.md](url) even im getting the same error. Kindly look into my code snapshots.
![config](https://cloud.githubusercontent.com/assets/18435594/22412775/fc902682-e6d7-11e6-9eed-fb10ae2a46a6.png)
![console](https://cloud.githubusercontent.com/assets/18435594/22412776/fc916308-e6d7-11e6-8ffc-12553273972e.png)
![module](https://cloud.githubusercontent.com/assets/18435594/22412777/fc916254-e6d7-11e6-8625-65ca37419e40.png)

**Comment by kekeh** [comment]
Your code seems to be ok.

Check example below. It is example application. It shows **mydatepicker** and **mydaterangepicker** on the browser and it uses **systemjs** loader. Download the **systemjstest.zip** file from the link below and do the following:

1. Extract zip
2. Go to the project folder and run: **npm install**
3. Build application: **npm run tsc**
4. Start the application: **npm start**
5. mydatepicker and mydaterangepicker is shown



[systemjstest.zip](https://github.com/kekeh/mydaterangepicker/files/738340/systemjstest.zip)

**Comment by imdivakar** [comment]
@kekeh thanks for your help actually i rectified this issue. I imported mydaterangepicker module in wrong module that's the issue. Ex: I'm going to use <my-date-range-picker> in login component which depends on login.module. Instead of importing mydaterangepicker module here i imported in app.module thats the issue.
Thanks again
