### ISSUE TITLE
How To Show Calendar With Today Date 

### ISSUE THREAD

**Issue by navi483** [kekeh/mydaterangepicker#100]
How To Show Calendar With Today Date If The Calendar is already set with some Default Date

Ex: My date picker text box is set With 02/02/2017  is Disabled still today date , How to show the selector from today date.

**Comment by kekeh** [comment]
You can use the defaultMonth attribute to open the calendar to the specific month. Here is documentation: https://github.com/kekeh/mydaterangepicker#defaultmonth-attribute

Here is an example. The example is from the mydapicker but the attribute works same way also with the date range picker: https://github.com/kekeh/mydatepicker/wiki/Initialize-with-defaultMonth-attribute
