### ISSUE TITLE
mydaterangepicker as single date picker

### ISSUE THREAD

**Issue by ofirrifo** [kekeh/mydaterangepicker#103]
thanks for great component

I'm using the date range picker and I want to use it as single date select instead of select range.

I saw you have another component mydatepicker but I prefer to use the same component of the range.

thanks

**Comment by kekeh** [comment]
Hi @ofirrifo 

You cannot select a single date with mydaterangepicker. If you want to select a single date you have to use mydapicker.

If you want to use one component for Both the date range and a single date one option is to use two date picker to select a range and one date picker select a date.
