### ISSUE TITLE
How to have only date picker instead of date range when needed?

### ISSUE THREAD

**Issue by ranga-sriram** [kekeh/mydaterangepicker#105]
I have a use case where some times I need to enable date range and at other times allow only for selecting a single date and not a range.  Is there an option where I can disable date range and use it to pick a single date?

**Comment by kekeh** [comment]
No there is not this kind of option, but you can use the mydatepicker https://github.com/kekeh/mydatepicker select a single date and the mydaterangepicker https://github.com/kekeh/mydaterangepicker to select a date range.
