### ISSUE TITLE
Had to inject mydaterangepicker into each component

### ISSUE THREAD

**Issue by alok-srivastav** [kekeh/mydaterangepicker#109]
Hey,
I don't understand the concept of injecting the mydaterangepicker into each component's module where I need this picker. Although I have already injected it at the top i.e. in app.module.ts.
Please explain!!

Thanks

**Comment by kekeh** [comment]
You need to define the **MyDateRangePickerModule** only once in top level @NgModule

```javascript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { MyTestApp } from './my-test-app';
import { MyDateRangePickerModule } from 'mydaterangepicker';

@NgModule({
    imports:      [ BrowserModule, MyDateRangePickerModule ],
    declarations: [ MyTestApp ],
    bootstrap:    [ MyTestApp ]
})
export class MyTestAppModule {}
```

Then you can use the mydatepicker all of the components of your application like this:
```html
<my-date-range-picker name="mydaterange" [options]="myDateRangePickerOptions"
                    [(ngModel)]="model" required></my-date-range-picker>
```
The **myDateRangePickerOptions** and the **model** variables are defined in component level.
