### ISSUE TITLE
UglifyJs - SyntaxError: Unexpected token: punc

### ISSUE THREAD

**Issue by oscdeveloper** [kekeh/mydaterangepicker#11]
I get this error:
`ERROR in assets/js/app.cc36d8f1cf6620984efe.js from UglifyJs
SyntaxError: Unexpected token: punc ({) [./~/mydaterangepicker/dist/my-date-range-picker.module.js:1,0]
`

Anyone knows the solution?

**Comment by kekeh** [comment]
What is version of mydaterangepicker? Are you trying to uglify the code or when the error occur?

**Comment by oscdeveloper** [comment]
I have in package.json
"mydaterangepicker": "^1.0.10",
well it takes the newest one.
I use webpack with uglifyJS

**Comment by kekeh** [comment]
As you can see below the **node_modules/mydaterangepicker/dist/my-date-range-picker.module.js** file is not in ES5 format. The module is Angular AOT compatible. 

I think you have to process with uglify only files under **node_modules/mydaterangepicker/bundles**.

```javascript
import { CommonModule } from "@angular/common";
import { NgModule } from "@angular/core";
import { MyDateRangePicker } from "./my-date-range-picker.component";
import { InputFocusDirective } from "./directives/my-date-range-picker.input.directive";
export var MyDateRangePickerModule = (function () {
    function MyDateRangePickerModule() {
    }
    MyDateRangePickerModule.decorators = [
        { type: NgModule, args: [{
                    imports: [CommonModule],
                    declarations: [MyDateRangePicker, InputFocusDirective],
                    exports: [MyDateRangePicker, InputFocusDirective]
                },] },
    ];
    /** @nocollapse */
    MyDateRangePickerModule.ctorParameters = [];
    return MyDateRangePickerModule;
}());
```

**Comment by oscdeveloper** [comment]
I switch code as:
"mydaterangepicker": "1.0.10", 
without ^ and it's working good.
I will try with Your solution later.
Thank You.

**Comment by kekeh** [comment]
You can use the latest version (**1.3.0**) if you import the **MyDateRangePickerModule** right way.

If you import the MyDateRangePickerModule this way you get that uglify error:
```javascript
import {MyDateRangePickerModule} from 'mydaterangepicker/dist/my-date-range-picker.module';
```
Importing this way works without errors:
```javascript
import {MyDateRangePickerModule} from 'mydaterangepicker';
```
