### ISSUE TITLE
use for one date only

### ISSUE THREAD

**Issue by CrackerakiUA** [kekeh/mydaterangepicker#115]
I am searching on the options and seems like there is none option to use this datepicker for pick only one date, due date for example.
I am looking for something like, catch date picked and close the datepicker after.
I know that you have two datepickers, and the second is for that purpose, but why should we install both when we can use this for both cases?

**Comment by tkstang** [comment]
Just click on the date twice which will set the date from for example July 17 - July 17, just write a function that parses that and checks if both dates are the same and if so that is your due date.
