### ISSUE TITLE
showDateRangeFormatPlaceholder - missed in model IMyOptions

### ISSUE THREAD

**Issue by oscdeveloper** [kekeh/mydaterangepicker#12]
Version: 1.3.0.
In `\node_modules\mydaterangepicker\dist\interfaces\my-options.interface.d.ts`
there is no option anymore:
`showDateRangeFormatPlaceholder`

**Comment by kekeh** [comment]
The **showDateRangeFormatPlaceholder** and the **customPlaceholderTxt** options removed. Instead of these options use the **placeholder** attribute. For example:

```html
<my-date-picker [options]="myDatePickerOptions" [placeholder]="placeholderTxt"
                (dateChanged)="onDateChanged($event)"></my-date-picker>
```

```ts
import {IMyOptions, IMyDateModel} from 'mydatepicker';

private myDatePickerOptions: IMyOptions = {
        dateFormat: 'dd.mm.yyyy'
        // other options
};

private placeholderTxt: string = 'Select date';

onDateChanged(event: IMyDateModel) {
        // date selected...
}
```

**Comment by oscdeveloper** [comment]
OK.
Please update readme.md ;)

**Comment by kekeh** [comment]
It is already updated: https://github.com/kekeh/mydaterangepicker#placeholder-attribute

**Comment by oscdeveloper** [comment]
Well, remove it from this paragraph:

    Example of the options data (not all properties listed):

    myDateRangePickerOptions: IMyOptions = {
        clearBtnTxt: 'Clear',
        beginDateBtnTxt: 'Begin Date',
        endDateBtnTxt: 'End Date',
        acceptBtnTxt: 'OK',
        dateFormat: 'dd.mm.yyyy',
        firstDayOfWeek: 'mo',
        sunHighlight: true,
        height: '34px',
        width: '260px',
        inline: false,
        selectionTxtFontSize: '15px',
        alignSelectorRight: false,
        indicateInvalidDateRange: true,
        showDateRangeFormatPlaceholder: false

**Comment by kekeh** [comment]
Now it is done.
