### ISSUE TITLE
Disable weekends

### ISSUE THREAD

**Issue by Arvn41** [kekeh/mydaterangepicker#142]
Hi,
Thanks for this package, I am trying to disable all weekends (Saturday and Sunday) is there is any option to do the same, tried with disableDates and working fine but need to disable all weekends.

**Comment by kekeh** [comment]
Not possible with this component. It is possible with this new date and date range picker:
- Repository: https://github.com/kekeh/angular-mydatepicker
- Demo page: https://kekeh.github.io/angular-mydatepicker/
