### ISSUE TITLE
(QUESTION) Date range selection

### ISSUE THREAD

**Issue by imdivakar** [kekeh/mydaterangepicker#15]
Hi @kekeh , it is possible to have option to select start date whenever user selects the first date**("Without Select Begin Date / End Date / Accept")** Buttons ? Most probably like bootstrap daterangepicker
Thanks in advance

**Comment by kekeh** [comment]
I added option **quickRangeSelect**. It true by default. It automatically select begin/end date. You can try it here: https://kekeh.github.io/mydaterangepicker

Accept button click is needed.

New version of the component is 1.3.6
