### ISSUE TITLE
QUESTION , How can i edit template ?

### ISSUE THREAD

**Issue by nicely** [kekeh/mydaterangepicker#16]
i want to re design this module , i can not find ant css or html template. Please help.

**Comment by kekeh** [comment]
Component code is under the **src/my-date-range-picker** folder: https://github.com/kekeh/mydaterangepicker/tree/master/src/my-date-range-picker

Template is **html** file and styles are in **css** file.

Easiest is to create own npm package of the component. Here are instructions on how to do it: https://github.com/kekeh/mydaterangepicker#development-of-this-component
