### ISSUE TITLE
Select Begin Date Callback

### ISSUE THREAD

**Issue by imdivakar** [kekeh/mydaterangepicker#18]
@kekeh Is there any callback function after begin date selected? like onDateRangeChanged

**Comment by kekeh** [comment]
No there is not. It Could be useful.

**Comment by kekeh** [comment]
I added new callback dateSelected. It is in version 1.3.5. Here is more information: https://github.com/kekeh/mydaterangepicker#dateselected-callback

**Comment by imdivakar** [comment]
Hi @kekeh that's great pal :) kudos and also if you provide me a way to select begin/end date through event trigger function like in dateSelected callback i want to select the selected date as begin/date directly from there means it will be advantageous for me!

**Comment by kekeh** [comment]
You can select a date range from outside of the component using **selDateRange** attribute as follows:
```html
<my-date-range-picker [options]="myOptions" [selDateRange]="selDateRange" 
                (dateRangeChanged)="onDateRangeChanged($event)"></my-date-range-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyOptions, IMyDateRange, IMyDateRangeModel} from 'mydaterangepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // other options here...
        dateFormat: 'dd.mm.yyyy'
    }

    private selDateRange: IMyDateRange = selectedDateRangeNormal:IMyDateRange = {beginDate: {year: 0, month: 0, day: 0}, endDate: {year: 0, month: 0, day: 0}};

    constructor() { }

    onDateRangeChanged(event: IMyDateRangeModel) {
        // Update value of selDateRange variable
        this.selDateRange = {beginDate: event.beginDate, endDate: event.endDate};
    }

    // Calling this function set begin and end date
    setDateRange() {
        this.selDateRange = {beginDate: {year: 2018, month: 10, day: 9}, endDate: {year: 2018, month: 10, day: 19}};
    }

    // Calling this function clears the selected date range
    clearDateRange() {
        this.selDateRange = '';
    }
}
```

**Comment by imdivakar** [comment]
hi @kekeh ya i know about this feature but i want something like, If i select any date it should automatically select it as begin/end date and vice versa. Just like bootstrap daterangepicker [http://www.daterangepicker.com/](url)

**Comment by kekeh** [comment]
I added option **quickRangeSelect**. It true by default. It automatically select begin/end date. You can try it here: https://kekeh.github.io/mydaterangepicker

**Comment by imdivakar** [comment]
Great dude! Nice work 👍
