### ISSUE TITLE
Issue with Angular2

### ISSUE THREAD

**Issue by w0bbes** [kekeh/mydaterangepicker#2]
Uncaught Error: Expected 'styles' to be an array of strings. zone.js?fad3:140

**Comment by kekeh** [comment]
If you are using **webpack** you can fix this error by installing:
**npm install to-string-loader --save-dev**
**npm install css-loader --save-dev**

and then add the following loader to your **webpack** config.file:
`
            {
                test: /\.css$/,
                loader: "to-string-loader!css-loader"
            }
`

**Comment by kekeh** [comment]
Now styles are inline parameter of the component. This is implemented in version 0.0.18.
