### ISSUE TITLE
Make the picker more user friendly

### ISSUE THREAD

**Issue by philipjohnfob** [kekeh/mydaterangepicker#22]
I see that it is quite hectic to select the start date, move to the next picker and then select the end date. After discussing with some end users, I see that it would be great to have multiple date pickers in order to select the start date and end date in one go.

Illustrated below.

Currently the picker looks like follows.
![2](https://cloud.githubusercontent.com/assets/25737029/23652071/37fc34da-0330-11e7-823a-660966f2f877.PNG)

I was thinking it would be great if we can have something like follows (with or without the cancel button).

![1](https://cloud.githubusercontent.com/assets/25737029/23652187/969b0908-0330-11e7-8621-091d775c027e.PNG)

**Comment by philipjohnfob** [comment]
I am sorry, I see that in v1.3.6, **quickRangeSelect** is added, which almost works.
But it works only after clearing the input area. It does not work after the user selects the range and clicks on Apply and tries to update the date again. In this case, they have to click on Clear / go to the end date tab and select the end date.

It would be great if this issue can be fixed.

**Comment by kekeh** [comment]
It is possible edit already selected range to open calendar and select the begin tab to edit the begin date or select the end tab to edit the end date. When ready click the apply button.

**Comment by philipjohnfob** [comment]
@kekeh Did you understand my point? :-)
I will give you the actual flow.

- Quick date range selection: true, Empty date range field.
- Expand date picker
- First click sets start date, second click sets end date. (automatically without moving to end date tab)
- Apply
- Again expand date picker
- First click sets start date, second click sets **start date again**, not end date. <- This is the issue

Need to manually click on end date tab and select the end date in the last step. Else you need to Clear and then it works fine.

**Comment by philipjohnfob** [comment]
Hi. Any updates on this?

**Comment by agnislav** [comment]
Hi @philipjohnfob , do you mean a behaviour like on kiwi.com? No edit mode, first and second clicks set start and end date? If so - I would vote for it.

**Comment by kekeh** [comment]
Hi @philipjohnfob 

I fixed your issue. Now the first click sets start date and the second click sets end date. Apply button click is optional and it is moved to the top of calendar.

You can try it here: https://kekeh.github.io/mydaterangepicker/

New version is 2.0.0
