### ISSUE TITLE
Disabled dates

### ISSUE THREAD

**Issue by jackrobertscott** [kekeh/mydaterangepicker#28]
Please can you add the functionality where a user may provide an array of dates (multiple different and unrelated dates) as an option to the picker and those dates would then be disabled on the calendar. As far as I am aware, the picker only supports disabling dates before and after certain a certain date but not individual dates. I am currently developing an app that depends on this functionality and I would be very grateful if you were able to add it.

Thank you!

**Comment by kekeh** [comment]
I added two new options: **disableDates** and **disableDateRanges**. For more info check here: https://github.com/kekeh/mydaterangepicker#options-attribute

This change is in version 1.4.3.
