### ISSUE TITLE
Localization, bootstrap

### ISSUE THREAD

**Issue by xtreemrage** [kekeh/mydaterangepicker#3]
Do you have an example on how to use localization with your datepicker?
Is it also possible to theme it to a bootstrap look and feel?

**Comment by kekeh** [comment]
This date range picker doesn't contain predefined locales. You have to localize by options attribute. The following properties must be localized:

| dayLabels     | {su: 'Sun', mo: 'Mon', tu: 'Tue', we: 'Wed', th: 'Thu', fr: 'Fri', sa: 'Sat'} | Day labels visible on the selector. |
| monthLabels   | { 1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun', 7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec' } | Month labels visible on the selector. |
| dateFormat   | yyyy-mm-dd      | Date format on the selection area and the callback. For example: dd.mm.yyyy, yyyy-mm-dd, dd mmm yyyy (mmm = Month as a text) |
| clearBtnTxt   | Clear      | Clear selected range button text. |
| beginDateBtnTxt   | Begin Date      | To begin date button text. |
| endDateBtnTxt   | End Date      | To end date button text. |
| acceptBtnTxt   | OK      | Accept date range button text. |
| selectBeginDateTxt  | Select Begin Date      | Select begin date text. |
| selectEndDateTxt   | Select End Date      | Select end date text. |

Put those properties to options attribute with any locale. You can also create multiple locales and change those attributes dynamically when the locale is changed.

Here is an example of usage of option attribute: https://github.com/kekeh/mydaterangepicker/tree/gh-pages/src/app/components/sample-date-range-picker-normal

You can override styles if you want. All styles are here: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.css

For example override title area background color:
.mydrp .titlearea {
    background-color: green;
}

Those overrides have to be loaded after the date range picker component has been loaded.

**Comment by xtreemrage** [comment]
Thanks for your quick response, it works. Although I don't know how to load the css after the component has been loaded. 

This is what I have: app.component.ts with the daterangepicker component and app.component.css. If I use the css in that file it won't override the component css. I use angular-cli to generate my angular 2 app and it has a styles.css that I can use to overide your styles. Don't know if that's the way to do it.

**Comment by kekeh** [comment]
Important key is not needed. For example if you load all js bundles in the **index.html** file (like webpack app). Some of the bundle contains the date picker. After that bundle you can define:

```javascript
<style>
    .mydrp .titlearea {
        background-color: green;
    }
</style>
```

and it overrides titlearea background without important key. This is not separate CSS file solution. But if you are using separate CSS file probably important key is needed.

**Comment by xtreemrage** [comment]
Thanks for your feedback

**Comment by kekeh** [comment]
Addition in my previous comment you can also put all to separate CSS file and use @import key like below:

```javascript
<style>
    @import "override.css";
</style>
```

**Comment by sametsafak** [comment]
Hi kekeh,

https://github.com/kekeh/mydaterangepicker/tree/gh-pages/src/app/components/sample-date-range-picker-normal this link doesn't work anymore. Could you update please?

**Comment by kekeh** [comment]
New link is: https://github.com/kekeh/mydaterangepicker/tree/gh-pages/src/app/sample-date-range-picker-normal

I have changed this project from webpack to angular-cli. That is why the link didn't work.

**Comment by sametsafak** [comment]
Thanks for the update! Now I am trying to change language dynamically.
