### ISSUE TITLE
Set date range on end date click, without "Accept"

### ISSUE THREAD

**Issue by agnislav** [kekeh/mydaterangepicker#30]
Hi

The daterangepicker is great. Me and my team very appreciate your efforts spent for it. The only 2 points exist that prevent us from using it.

- The first is described in #22.
- The second is about using "Accept" button. Is it possible to not use it?

As an example of what we're looking for you can take a look at [kiwi.com](kiwi.com). The date range selector there doesn't require additional clicks.

Any chances this can be implemented in the yours?

**Comment by kekeh** [comment]
Hi @agnislav 

I fixed your issue. Now the first click sets start date and the second click sets end date. Apply button click is optional and it is moved to the top of calendar.

You can try it here: https://kekeh.github.io/mydaterangepicker/

New version is 2.0.0

**Comment by agnislav** [comment]
Thanks a lot for such prompt fix!
