### ISSUE TITLE
Use myDateRangePicker as myDatePicker

### ISSUE THREAD

**Issue by agnislav** [kekeh/mydaterangepicker#31]
Hi, @kekeh ,

Saying, I want to grant a user an opportunity to use certain date and date range both (like on kiwi.com). Should I load and use both mydatepicker and mydaterangepicker or the second one can work as the first one?

Thanks!

**Comment by kekeh** [comment]
Maybe you can implement it using two date picker. Checkbox "select range" shows second date picker and you can use disable date option to prevent user to select "wrong" dates.

If I change date range picker to work as date picker, it is quite big change.

**Comment by agnislav** [comment]
We've went this way. Thanks!
