### ISSUE TITLE
Enable specific dates

### ISSUE THREAD

**Issue by chandanch** [kekeh/mydaterangepicker#32]
Is there a way to enable only specific dates?  The disabledDates option allows to disable only specific dates. But in a scenario where some dates must be enabled in a year and disable other dates,  enableDates option will be more effective and useful.

**Comment by kekeh** [comment]
I added option **enableDates**. For example use it as follows:

```javascript
private myOptions: IMyOptions = {
    minYear: 1900,
    maxYear: 2100,
    disableDateRanges: [{
        beginDate: {year: 1900, month: 1, day: 1}, 
        endDate:{year: 2100, month: 12, day: 31}}
    ],
    enableDates: [
        {year: 2017, month: 1, day: 14}, 
        {year: 2017, month: 1, day: 15}, 
        {year: 2017, month: 1, day: 20}
    ]
};
```

Above example 
1. set min year 1900
2. set max year 2100
3. disables all dates between 1.1.1900 and 31.12.2100
4. enables dates 14.1.2017, 15.1.2017 and 20.1.2017

enabled dates are selectable

Update the latest version **2.1.1** to use this feature.

**Comment by chandanch** [comment]
Thanks, I updated to 2.1.1 and its working as expected, Can the same be added for mydatepicker as well?

**Comment by kekeh** [comment]
It ia already in mydatepicker. Option name is enableDays.

**Comment by chandanch** [comment]
Okay Thanks

**Comment by chandanch** [comment]
In my application I'm using mydatepicker and mydaterangepicker, since the mydatepicker has **enableDays** options and mydaterangepicker has **enabelDates** option. We cannot  import `IMyOptions` from mydatepicker and mydaterangepicker like this:

```typescript
import {IMyOptions} from 'mydaterangepicker';
// Error: Duplicate identifier
import {IMyOptions} from 'mydatepicker';
```
I will need to enable specific dates in both the datepicker components. How can I achieve this?

**Comment by kekeh** [comment]
Probably you need to create own component to both mydatepicker and mydaterangepicker.
