### ISSUE TITLE
how to clear the daterange text from outside the datepicker

### ISSUE THREAD

**Issue by gkgithub** [kekeh/mydaterangepicker#33]
I need a case where i need to reset the date range picker text back to place holder text when selected some other item in my component page. Also, i made showClearDateRangeBtn to false. I am trying to reset the model to {} or {beginDate:"", endDate:""} and different other options. None of them working.

**Comment by kekeh** [comment]
Here is an example: https://github.com/kekeh/mydaterangepicker/issues/24
