### ISSUE TITLE
Show a specific month when the calendar is opened

### ISSUE THREAD

**Issue by chandanch** [kekeh/mydaterangepicker#34]
When the calendar is opened instead of showing the current month, Is there an option to show a specific month? With the `enableDates` , `disabledDateRanges` or `disableDates` it is possible to disable an entire month. For example, if all the days of the current month is disabled like this:

````typescript
this.myDatePickerOptions = {
    dateFormat : 'mm/dd/yyyy',
    disableDateRanges :  [
            {
                begin: {year: 2017, month: 4, day: 1}, 
                end: {year: 2017, month: 4, day: 30}
            }
        ],
    enableDates : [
        {year : 2017, month : 3, day : 21}, 
        {year : 2017, month : 3, day : 12}
    ]
}
````
Now all the days in  the current month April 2017 is disabled, When the user opens the calendar instead of showing the current month it will be more user-friendly if we show the month for which the dates are enabled. 
So, Is there an option to go to show a specific month or maybe a year when the calendar is open?

**Comment by kekeh** [comment]
You can use the **defaultMonth** attribute to show specific month. It works if the date range is not selected or the default date range is not set. Use it as follows:

```html
<my-date-range-picker [options]="myOptions" [defaultMonth]="defaultMonth" 
    (dateRangeChanged)="onDateRangeChanged($event)"></my-date-range-picker>
```

```javascript
// opens calendar March of 2017 by default
private defaultMonth: string = '03/2017'
```

**Comment by chandanch** [comment]
Thanks​ i will check the docs
