### ISSUE TITLE
reset inputfield - binding not working

### ISSUE THREAD

**Issue by aavelyn** [kekeh/mydaterangepicker#36]
Hi there, first of all great component!

currently i'm having trouble resetting the input display value, once the form is submitted.
There seems to be some problem with the binding since neither ngModel (template form) nor formControllName (reactive) seems to work. I seems the binding works only one way (read).

**Comment by kekeh** [comment]
Try resetting to put empty string to value of model. Does it work?

**Comment by kekeh** [comment]
If you are not setting initial date range you can try also this:

```html
<my-date-range-picker [options]="myOptions" [selDateRange]="selDateRange" 
                (dateRangeChanged)="onDateRangeChanged($event)"></my-date-range-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyOptions, IMyDateRangeModel} from 'mydaterangepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // other options here...
        dateFormat: 'dd.mm.yyyy'
    }

    private selDateRange: string = '';

    constructor() {}

    onDateRangeChanged(event: IMyDateRangeModel) {
        // Update value of selDateRange variable
        this.selDateRange = {beginDate: event.beginDate, endDate: event.endDate};
    }

    // Calling this function clears the selected date range
    clearDateRange() {
        this.selDateRange = '';
    }
}
```

**Comment by aavelyn** [comment]
oh damn, sorry! it seems i've posted the issue in the wrong thread. The issue i'm having is with the date picker not the date range picker
