### ISSUE TITLE
Weird bundle view

### ISSUE THREAD

**Issue by agnislav** [kekeh/mydaterangepicker#37]
Hi,

We've found a strange view in our app bundle, could you take a look at it, please? https://goo.gl/bywyN0

The strange point is that the datepicker seems to be included in the bundle twice: in vendor part and in our app part both. As this is something we haven't seen with other modules, could I ask you to verify whether it's expected behaviour for the picker?

Thanks!

**Comment by kekeh** [comment]
What tool you are using to bundles?

**Comment by agnislav** [comment]
That's a [source map explorer] (https://www.npmjs.com/package/source-map-explorer)

**Comment by kekeh** [comment]
I tried with this: https://github.com/kekeh/mydatepicker/tree/gh-pages project and I saw mydatepicker only in the **dist/app.js** bundle. This is webpack project. 

I tried also this: https://github.com/kekeh/mydaterangepicker/tree/gh-pages which is mydaterange picker project. I saw mydaterangepicker only in the **dist/vendor.bundle.js** bundle. This is angular-cli project.

Have you accidentally import mydatepicker in your vendor.ts file? Are you using angular-cli or similar predefined configuration?

**Comment by agnislav** [comment]
We use angular-cli. We have no vendor.ts we do manage. I've got few more options to try in our app. If you have any more suggestions to check - I'll appreciate it.

**Comment by kekeh** [comment]
How you built you application before source-map-explorer check? I will build my application same way and check again after that.

Can you search MyDatePickerModule and MyDatePicker strings from your vendor bundle. They are ng module class and component class of mydatepicker. Maybe you have already do this?

**Comment by agnislav** [comment]
The only difference I've found at the moment is a level of importing a MyDatePickerModule.

Your app imports it directly: `AppModule` <-- `MyDatePickerModule`.
In our app we have a bit deeper structure: `AppModule` <-- `SearchBarModule` <-- `MyDatePickerModule`.

Hope it helps. We continue the investigation on our side as well.

Thanks a lot for your help.

**Comment by agnislav** [comment]
Hi, 

I've reproduced the same on the empty repo.

[repo link](https://github.com/agnislav/datepicker-bundle-issue)

Steps:
```
npm i
ng build --no-vendor --prod --aot --sourcemap
./node_modules/.bin/source-map-explorer ./dist/main.7368344916dd16b0723a.bundle.js
```

My screenshots: [link1](https://goo.gl/tX4s01), [link2](https://goo.gl/CuZRsg)

**Comment by kekeh** [comment]
It is **entryComponents** in **@NgModule** which causes this issue:

```javascript
@NgModule({
    imports: [CommonModule, FormsModule],
    declarations: [NgxMyDatePicker, NgxMyDatePickerDirective, FocusDirective],
    entryComponents: [NgxMyDatePicker],  // this caused issue
    exports: [NgxMyDatePickerDirective]
})
export class NgxMyDatePickerModule {
}
```

I don't know how to prevent this issue. If I remove the entryComponents the date picker doesn't work. Is this issue only in ngx-mydatepicker? You have created this issue to mydaterangepicker repository.

**Comment by agnislav** [comment]
Hi @kekeh , 

I asked the question in the angular gitter chat and got the following answer:

> one is the component, the other is the compiled template (the ngfactory)

So, I assume that the current behaviour is expected and my question was due to my lack of knowledge. Sorry for the time spent.
