### ISSUE TITLE
NgModel binding sometimes returns empty string

### ISSUE THREAD

**Issue by Tuupertunut** [kekeh/mydaterangepicker#39]
Reproduction:
1. Two-way bind some variable `model` to `[(ngModel)]` of the picker.
2. Watch the value of that variable as you edit the picker.

Expected behavior:
When a date range is given in the picker, the `model` variable should have a date range model object as value. When the picker is cleared, `model` should either change to `null` or some special case of date range model, representing an empty date range.

Current behaviour:
When the picker is cleared, `model` gets an unexpected value of `""`, an empty string. This means there is no defined type for `model`, it may sometimes be a date range model (`IMyDateRangeModel`) and sometimes a `string`.

**Comment by kekeh** [comment]
It returns IMyDateRangeModel if a range is selected and it is valid. Otherwise it returns an empty string.

**Comment by Tuupertunut** [comment]
Shouldn't it rather return `null` or some kind of empty date range model object? Currently the return type is `IMyDateRangeModel | string` which is not very clean and you have to do type checkings every time you use it.

**Comment by kekeh** [comment]
It is difficult to change because it is api. Also I use empty string because you can use required validator easily. If it is null I don't know is required validator is working..

**Comment by kekeh** [comment]
I changed functionality so that if value of model is invalid it is null. This change is in version 4.0.0.
