### ISSUE TITLE
editableMonthAndYear removed in version 3.0.0

### ISSUE THREAD

**Issue by kekeh** [kekeh/mydaterangepicker#41]
Option **editableMonthAndYear** removed. Added options **monthSelector** and **yearSelector**. By default the **monthSelector** and the **yearSelector** are **true**.

If **monthSelector** is **true** a list of months is shown if a month label is clicked. For example:

![month-selector](https://cloud.githubusercontent.com/assets/11028839/25693558/9b59d64a-30b2-11e7-879d-25e577515003.png)

If **yearSelector** is **true** a list of years is shown if a year label is clicked. For example:

![year-selector](https://cloud.githubusercontent.com/assets/11028839/25693568/a0445e14-30b2-11e7-90b7-f3be45ba5db0.png)

You can set both values to false if you don't need this kind of feature.

You can test functionality here: http://kekeh.github.io/mydaterangepicker/

**Comment by adamfoerster** [comment]
Awesome, the selection screens will be much more useful.
