### ISSUE TITLE
Unable to edit and select future ranges

### ISSUE THREAD

**Issue by airyz** [kekeh/mydaterangepicker#42]
How to reproduce: 
1. Select a date range e.g. 4/5/2017 - 5/5/2017
2. Open the data picker and try to select new date range that starts after your last date e.g. 6/5/2017-7/5/2017
Problem: Any date after the "To" date is disabled so I cannot edit a range with future date ranges.

**Comment by kekeh** [comment]
I fixed this. I changed functionality. You can test it here: https://kekeh.github.io/mydaterangepicker/

New version of the component is: 4.1.0
