### ISSUE TITLE
inline mode, disableDateRanges issue

### ISSUE THREAD

**Issue by 91debug** [kekeh/mydaterangepicker#43]
I need to set 'disableDateRanges' option dynamically. (inline true mode)

However, if I set this option, the calendar is moved to today's date.

how to solve this problem?

**Comment by kekeh** [comment]
Try the **defaultMonth** attribute: https://github.com/kekeh/mydaterangepicker#defaultmonth-attribute

For example set August of 2016 to calendar view:
```html
<my-date-range-picker [options]="myDateRangePickerOptions" [defaultMonth]="defaultMonth"
                   (dateRangeChanged)="onDateRangeChanged($event)"></my-date-range-picker>
```
```javascript
private defaultMonth: string = '2016.08';
```
This attribute can be set dynamically.
