### ISSUE TITLE
IMyOptions require unique names for daterange- and datepicker because of incompatibility

### ISSUE THREAD

**Issue by seawave23** [kekeh/mydaterangepicker#45]
The IMyOptions interfaces for the daterange- and the datepicker are incompatible. Could you please give them unique names that both, the datepicker and the daterangepicker, could be used together in the same component if necessary?

**Comment by kekeh** [comment]
Now there are unique names to both option interfaces:
- mydatepicker: **IMyDpOptions**
- mydaterangepicker: **IMyDrpOptions**

Update components to latest versions:
- mydatepicker: 2.0.5
- mydaterangepicker: 4.1.1

If this does not work let me know.
