### ISSUE TITLE
Feature Request: Possibility of changing the ''.mydrp .disabled" style

### ISSUE THREAD

**Issue by adamfoerster** [kekeh/mydaterangepicker#46]
Hi there.
Currently (as of version 3.0.1), when I select a date range the previous and subsequent days receive a ```disabled``` class which has the following css attached:
```
.mydrp .disabled {
    cursor: default !important;
    color: #444 !important;
    background: #FBEFEF !important;
```
Since these css have the ```!important``` I cannot restyle them without forking the project entirely.
It would be nice if the css of this class didn't have the ```!important``` so I could override the css.

Minor details not standing, this is the best date range selector for Angular so far. Keep the good work!

**Comment by kekeh** [comment]
I have totally removed that feature. Install the latest version 4.1.2

**Comment by adamfoerster** [comment]
Installed it. Works like a charm. Thanks!

**Comment by dinesh-here** [comment]
Hi @kekeh ,

disabled class issue still persists in latest version & 4.12 also. Please check the stackblitz.

https://stackblitz.com/edit/angular-m3fhyj
