### ISSUE TITLE
Error: compile error on 'core-js'

### ISSUE THREAD

**Issue by poppo191** [kekeh/mydaterangepicker#5]
Hi, I got the error after start server

This is error message: 
```
/node_modules/mydaterangepicker/dist/my-date-range-picker.component.d.ts:1:1 
    Cannot find type definition file for 'core-js'.
[default] Checking finished with 1 errors
```

I've checked in the package file too. Already installed it.
Package file:
```
...,
"core-js": "^2.4.1",
...
```

Please help me fix it.
Thank you :)

**Comment by kekeh** [comment]
It tries to find package under **your_app/node_modules/mydaterangepicker/node_modules** but there is not core-js.

What kind of configuration you have? Are you using webpack, angular-cli?

**Comment by poppo191** [comment]
Hi @kekeh, I used webpack and about the configuration. I clone the configuration from ` https://github.com/akveo/ng2-admin

**Comment by kekeh** [comment]
@poppo191 

I was able to add mydaterangepicker to ng2-admin dashboard. I did not find any problem. I took latest version from the mydaterangepicker and the ng2-admin.

For example in dashboard.module.ts file:
```javascript
// other imports...
import { MyDateRangePickerModule } from 'mydaterangepicker';
import {SampleDateRangePickerNormal} from '../sample-date-range-picker/sample-date-range-picker-normal'

@NgModule({
  imports: [
    // other modules...
    MyDateRangePickerModule
  ],
  declarations: [
    // other declarations...
    SampleDateRangePickerNormal
  ],
  providers: [
    // providers...
  ]
})
```

In dasboard.html add:
```html
<div class="row">
    <sample-date-range-picker-normal></sample-date-range-picker-normal>
</div>
```
Under the **src/app/pages** create the **sample-date-range-picker** folder and add **html** and **ts** files from here to this folder:
https://github.com/kekeh/mydaterangepicker/tree/master/sampleapp/sample-date-range-picker-normal

After everything works you can rename each file and variable and remove extra code which is part of sampleapp. Can you try that.

**Comment by poppo191** [comment]
Hi @kekeh Thank you for your suggestion. I've found the problem on import module
`import { MyDateRangePickerModule } from "mydaterangepicker/dist";` 

I will close this issue.
Thank you
