### ISSUE TITLE
Mydaterangepicker with material icons

### ISSUE THREAD

**Issue by kirtiesl** [kekeh/mydaterangepicker#50]
How can we replace current mydaterangepicker  icons with material icons in angular 4??

**Comment by kekeh** [comment]
Now icons are embedded to CSS file: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.css#L507

I have used [Fontello](http://fontello.com/) to generate icons. I don't know does material icons work this way.

You can also edit template to add material icons: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.html

Maybe you have to create own version of the component. You can start from here: https://github.com/kekeh/mydaterangepicker#development-of-this-component
