### ISSUE TITLE
Next Year button is disabled

### ISSUE THREAD

**Issue by tamarshore** [kekeh/mydaterangepicker#51]
Hi, 

Thanks for the great date range picker.
I've an issue with the next year button. in the beginning it's disabled and only when I press the previous year button the next button is enabled (and then i can reach to the year I've wanted).

I can see in your source the headerbtndisabled class on the button, but there is no trigger in my code for it. (and I've tried to play with the since and until properties of the IMyOptions and such).

Can you please help me?:)

**Comment by kekeh** [comment]
If you have set **maxYear** option to some year then the next year button is disabled if the value of maxYear is next year on calendar.

Or if you have used **disableSince** option and the next year is fully disabled by disableSince option. You can control this with **disableHeaderButtons** option. Set it to **false**.

The disableHeaderButtons option affects only the disableSince option. Not the maxYear option.

If you are using old version. Please update the latest version at first.

**Comment by tamarshore** [comment]
Thanks for your response.
My version in updated, and as I said I have nothing in my code that triggers it.
This is my IMyOptions:
public datePickerOptions: IMyOptions = {
    dateFormat: 'dd.mm.yyyy',
    dayLabels: {
      su: this.translate.instant('calender.days.sun'),
      mo: this.translate.instant('calender.days.mon'),
      tu: this.translate.instant('calender.days.tue'),
      we: this.translate.instant('calender.days.wed'),
      th: this.translate.instant('calender.days.thu'),
      fr: this.translate.instant('calender.days.fri'),
      sa: this.translate.instant('calender.days.sat')
    },
    monthLabels: {
      1: this.translate.instant('calender.month.jan'),
      2: this.translate.instant('calender.month.feb'),
      3: this.translate.instant('calender.month.mar'),
      4: this.translate.instant('calender.month.apr'),
      5: this.translate.instant('calender.month.may'),
      6: this.translate.instant('calender.month.jun'),
      7: this.translate.instant('calender.month.jul'),
      8: this.translate.instant('calender.month.aug'),
      9: this.translate.instant('calender.month.sep'),
      10: this.translate.instant('calender.month.oct'),
      11: this.translate.instant('calender.month.nov'),
      12: this.translate.instant('calender.month.dec')
    },
    showClearBtn: false,
    showClearDateRangeBtn: false
  };

**Comment by kekeh** [comment]
I tried to reproduce but not succeeded. I tried this kind of config:

    <my-date-range-picker [options]="datePickerOptions"></my-date-range-picker>

    private datePickerOptions: IMyOptions = {
        dateFormat: 'dd.mm.yyyy',
        showClearBtn: false,
        showClearDateRangeBtn: false
    };

Can you temporary remove the day and month labels from the config and try again.

**Comment by tamarshore** [comment]
Doesn't work...
