### ISSUE TITLE
How to display clear and calendar icon button in front of input field?

### ISSUE THREAD

**Issue by 02harleen** [kekeh/mydaterangepicker#54]
Is it possible to change the location of clear and calendar button? And how to use bootstrap icon?

**Comment by kekeh** [comment]
Position of the buttons are not configurable. If you want to change place of them you have create own version of the component. You can start from here: https://github.com/kekeh/mydaterangepicker#development-of-this-component

Icons are embedded to the CSS file: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.css#L512

I have used [Fontello](http://fontello.com/) to generate embedded icons. But you can also edit HTML template and change class names of the icons to bootstrap classes. HTML template is here: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.html

class name of the icon is **mydrpicon**. You can search this string.
