### ISSUE TITLE
Is there a way to disable past date from today

### ISSUE THREAD

**Issue by jtaoufik** [kekeh/mydaterangepicker#56]
I'd like to make the component offer only date from tomorrow to the next year, and also control the amount you can select depending of the balance (like 30 balance equals 15 days)  a user has.

**Comment by kekeh** [comment]
You can use **disableUntil** option to disable past dates from today as follows:
```html
<my-date-range-picker [options]="myOptions"></my-date-range-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyDrpOptions} from 'mydaterangepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyDrpOptions {
        // other options here...
        disableUntil: {year: 0, month: 0, day: 0}
    }

    constructor() {}

    // Calling this function set disableUntil value from today
    disableUntil() {
        let d: date = new Date();
        let copy = this.getCopyOfOptions();
        copy.disableUntil = {year: d.getFullYear(), 
                             month: d.getMonth() + 1, 
                             day: d.getDate()};
        this.myOptions = copy;
    }

    // Returns copy of myOptions
    getCopyOfOptions(): IMyDrpOptions {
        return JSON.parse(JSON.stringify(this.myOptions));
    }
}
```

If you want to disable future dates (from next year) you can use **disableSince** option. You can also use the **disableDates** option to disable single dates one by one or use the **disableDateRanges** option to disable multiple date ranges.

For example if you use **disableDateRanges** option and want to enable some dates on range you can use **enableDates** option.

You can change any option dynamically like disableUntil example above.

Read details of options from here: https://github.com/kekeh/mydaterangepicker#options-attribute

Did this answer to your question?

**Comment by jtaoufik** [comment]
Yes you answered the question, thank you very much mate 🥇
