### ISSUE TITLE
'rootDir' is expected to contain all source files.

### ISSUE THREAD

**Issue by oscdeveloper** [kekeh/mydaterangepicker#6]
I get error when I build app
`
ERROR in X/tsconfig.json
error TS6059: File 'X/node_modules/mydaterangepicker/index.ts' is not under 'rootDir' 'X/src'. 'rootDir' is expected to contain all source files.

ERROR in X/tsconfig.json
error TS6059: File 'X/node_modules/mydaterangepicker/src/my-date-range-picker/directives/my-date-range-picker.input.directive.ts' is not under 'rootDir' 'X/src'. 'rootDir' is expected to contain all source files.

ERROR in X/tsconfig.json
error TS6059: File 'X/node_modules/mydaterangepicker/src/my-date-range-picker/interfaces/index.ts' is not under 'rootDir' 'X/src'. 'rootDir' is expected to contain all source files.

ERROR in X/tsconfig.json
error TS6059: File 'X/node_modules/mydaterangepicker/src/my-date-range-picker/interfaces/my-date-range.interface.ts' is not under 'rootDir' 'X/src'. 'rootDir' is expected to contain all source files.`

Anyone knows what happened?

**Comment by kekeh** [comment]
If you are using webpack try **tsconfig.json** like this:
https://github.com/kekeh/mydaterangepicker/blob/gh-pages/tsconfig.json

**exclude** node_modules and **include** you own source files. This https://github.com/kekeh/mydaterangepicker/tree/gh-pages application is done with webpack and it is running here: https://kekeh.github.io/mydaterangepicker/

Let me know is this working or not.

**Comment by oscdeveloper** [comment]
Your solution works correctly :) , but I resolved it in different way.
In app.module.ts I point directly to JS file:
`import {MyDateRangePickerModule} from 'mydaterangepicker/dist/my-date-range-picker.module';`

Thanks anyway for help!

**Comment by kekeh** [comment]
You can try the latest **1.3.0** version. The npm package doesn't contain typescript files any more.

You can import module this way:
```javascript
import {MyDateRangePickerModule} from 'mydaterangepicker';
```
