### ISSUE TITLE
Disable data range

### ISSUE THREAD

**Issue by MohamedAmineOuali** [kekeh/mydaterangepicker#61]
Hello,

I think that there is a problem when trying to disable a range of date could do verify this please.

this.myDatePickerOptions.disableDateRanges=[{beginDate: {year: 2017, month: 7, day: 21}, endDate: {year: 2017, month: 7, day: 25}}];

I use this in my component to disable a DateRanges but it didn't work.
I am also using  disableSince  and it works.
is there a conflict between the two of them 

Update:

I don't think there is a conflict I tried to set this when constructing the Object and it works is there a problem when assigning this attribute "disableDateRanges"

thank you.

**Comment by kekeh** [comment]
Try to disable dynamically. Example below:

```html
<my-date-range-picker [options]="myOptions" 
                (dateRangeChanged)="onDateRangeChanged($event)"></my-date-range-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyDrpOptions, IMyDateRangeModel} from 'mydaterangepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyDrpOptions {
        // other options here...
        disableDateRanges: []
    }

    constructor() {}

    onDateRangeChanged(event: IMyDateRangeModel) {
        // date range selected
    }

    // Calling this function disable date range
    disableDateRange() {
        let copy = this.getCopyOfOptions();
        copy.disableDateRanges = [{beginDate: {year: 2017, month: 7, day: 21}, endDate: {year: 2017, month: 7, day: 25}}];
        this.myOptions = copy;
    }

    // Returns copy of myOptions
    getCopyOfOptions(): IMyDrpOptions {
        return JSON.parse(JSON.stringify(this.myOptions));
    }
}
```
