### ISSUE TITLE
How to set default current date selected?

### ISSUE THREAD

**Issue by 02harleen** [kekeh/mydaterangepicker#62]
Hi, I have used this plugin for filter data. 
My query: - If the page is load first time, so that time the current date is selected. This current date is the end date. If the user selects only start date and does not select end date so that time the current date is end date by default and fetch the data according to date range If user select start date and end date so fetch data according to a date range. 

So my question is how to set current date is end date and change according to user selection.

**Comment by kekeh** [comment]
You can set both start and end date at the same time. Not possible set them separately. For example set default range using **ngModel** binding:
```html
<my-date-range-picker name="myDateRange" [options]="myOptions" 
    [(ngModel)]="model" required></my-date-range-picker>
```

```javascript
model: any = {
    beginDate: {year: 2018, month: 10, day: 9}, 
    endDate: {year: 2018, month: 10, day: 19}
};
```

Does this answer to your question?

**Comment by JuliaRakitina** [comment]
Does not work
