### ISSUE TITLE
How to automatically move to end-date after choosing beginning date.

### ISSUE THREAD

**Issue by einsamer1203** [kekeh/mydaterangepicker#65]
Currently, after choosing beginning date, we need to click to "End Date" button to choose the end date.
Could we programmatically move to end date right after pick the start date?

**Comment by kekeh** [comment]
You can do it as follows:
```html
<!-- add mydrp local variable and dateSelected callback -->
<my-date-range-picker [options]="myDateRangePickerOptionsNormal" 
    #mydrp="mydaterangepicker"
    (dateRangeChanged)="onDateRangeChanged($event)"
    (dateSelected)="onDateSelected($event)"></my-date-range-picker>
```
```javascript
import {Component, OnInit, ViewChild} from '@angular/core';
import {IMyDateSelected, IMyDateRangeModel, MyDateRangePicker} from 'mydaterangepicker';

@ViewChild('mydrp') mydrp: MyDateRangePicker;

onDateRangeChanged(event: IMyDateRangeModel) {
    // date range selected
}

onDateSelected(event: IMyDateSelected) {
    if (event.type === 1) {
        let date: Date = new Date(event.jsdate.getTime());
        // add for example 5 days to start date and set created date to end date
        date.setDate(date.getDate() + 5);
        this.mydrp.selectEndDate({
                year: date.getFullYear(), 
                month: date.getMonth() + 1, 
                day: date.getDate()
        });
        this.mydrp.rangeSelected();
    }

}
```
In example when you select a start date an end date is automatically selected and it is start date + 5.

**Comment by einsamer1203** [comment]
Thank you, Kekeh, your answer help me to understand deeper the library.
Actually, I think I don't mean that auto-process.
I just want to do exact same thing in your example. When we pick the start date, the calendar automatically moves to the tab to choose the end date. As the normal configuration, I can do it when the calendar render. But when I modify the first date, it doesn't  work like that.

**Comment by einsamer1203** [comment]
Oh, it's just worked normally without any additional config. Maybe the error happens when I update your lib into the new version.
Sorry for this disturb and thanks for your help.
