### ISSUE TITLE
UserDateRangeInput

### ISSUE THREAD

**Issue by alexdmitbor** [kekeh/mydaterangepicker#67]
Hi!

I'd like to get event when user edit the value of date. But when the value bacomes as empty string func onUserDateRangeInput(value: string) doesnt emit any event. E.g. user enters something like "123" and then starts deleting, inputFieldChanged doesnt tell me anything. 

As i note, when the value of date is valid, this event truely tells me that now value of date = "".

Any idea of this?

**Comment by kekeh** [comment]
You have to do it this way:
```html
<my-date-range-picker [options]="myDateRangePickerOptions" 
    (inputFieldChanged)="onInputFieldChanged($event)"></my-date-range-picker>
```

```javascript
import {IMyDrpOptions, IMyInputFieldChanged} from 'mydaterangepicker';


```

**Comment by kekeh** [comment]
You have to do it this way:
```html
<my-date-range-picker [options]="myDateRangePickerOptions" 
    (inputFieldChanged)="onInputFieldChanged($event)"></my-date-range-picker>
```

```javascript
import {IMyDrpOptions, IMyInputFieldChanged} from 'mydaterangepicker';

// other code...

onInputFieldChanged(event: IMyInputFieldChanged) {
    console.log('onInputFieldChanged(): Value: ', event.value, ' - dateRangeFormat: ', event.dateRangeFormat, ' - valid: ', event.valid);
}
```
Above in the **onInputFieldChanged** function the property **event.value** indicates value of input box every time when it change. When value of the **event.value** is empty string you know the input box is also empty.

You can test here: https://kekeh.github.io/mydaterangepicker

open console of the browser to see all messages. Then type date range to the input field. Notice all message begin **onInputFieldChanged():**.

**Comment by alexdmitbor** [comment]
Ok, i got it.

As i realized, **onInputFieldChanged** function doesnt idicate empty string when data is invalid? E.g. when i manually write "123" and then delete it, console tells me:

onInputFieldChanged(): Value:  123  - dateRangeFormat:  dd mmm yyyy - dd mmm yyyy  - valid:  false
onInputFieldChanged(): Value:  12  - dateRangeFormat:  dd mmm yyyy - dd mmm yyyy  - valid:  false
onInputFieldChanged(): Value:  1  - dateRangeFormat:  dd mmm yyyy - dd mmm yyyy  - valid:  false

But when i set date using calendar, and then delete:

onInputFieldChanged(): Value:  02 Aug 2017 - 10 Aug 2017  - dateRangeFormat:  dd mmm yyyy - dd mmm yyyy  - valid:  true
onInputFieldChanged(): Value:    - dateRangeFormat:  dd mmm yyyy - dd mmm yyyy  - valid:  false
