### ISSUE TITLE
Possible to change "Select end Date"

### ISSUE THREAD

**Issue by cesarpizolato** [kekeh/mydaterangepicker#68]
When I select any date, datepicker shows a message: "date - Select End Date" and wait to user select end Date. Is it possible to change this message? I want to translate this to Portuguese.

**Comment by kekeh** [comment]
There are **selectBeginDateTxt** and **selectEndDateTxt** options. Check the **options** attribute: https://github.com/kekeh/mydaterangepicker#options-attribute
