### ISSUE TITLE
Disable dates?

### ISSUE THREAD

**Issue by realcnbs** [kekeh/mydaterangepicker#7]
Looking at the source code i couldn't understand how `disableSince` could be controlled from outside. Any hints?

**Comment by kekeh** [comment]
I added the **disableUntil** and the **disableSince** options also to **range** picker. These are added to version 1.0.15.

Here is online demo: https://kekeh.github.io/mydaterangepicker/#inlinemode

Here is code example how these option can be controlled from outside: https://github.com/kekeh/mydaterangepicker/tree/master/sampleapp/sample-date-range-picker-inline
