### ISSUE TITLE
How to use custom dateFormat like :- DD/MM/YYYY ?

### ISSUE THREAD

**Issue by 02harleen** [kekeh/mydaterangepicker#70]
Please tell us how to use custom date format.
Date format is:-
1.DD/MM/YYYY
2.DD-MM-YYYY
3.MM/DD/YYYY
4.MM-DD-YYYY

This is my custom format please tell us how to use this format?

**Comment by kekeh** [comment]
You have to use lowercase letters. For example:
```javascript
dateFormat: 'dd/mm/yyyy'
// or
dateFormat: 'dd-mm-yyyy'
// or
dateFormat: 'mm/dd/yyyy'
// or
dateFormat: 'mm-dd-yyyy'
```
