### ISSUE TITLE
Set date range coming from database, i am using formcontrol

### ISSUE THREAD

**Issue by ketanbgm** [kekeh/mydaterangepicker#74]

**Comment by ketanbgm** [comment]
how to set the daterange

**Comment by kekeh** [comment]
Here is an example which uses reactive forms: https://github.com/kekeh/mydaterangepicker#2-reactive-forms

You can use setValue() function of Angular.

**Comment by ketanbgm** [comment]
setDateRange(): void {
    // Set date range (today) using the setValue function
    let date = new Date();
    this.form.setValue({
      bookingdates: {
        beginDate: {
          year: date.getFullYear(),
          month: date.getMonth() + 1,
          day: date.getDate()
        },
        endDate: {
          year: date.getFullYear(),
          month: date.getMonth() + 1,
          day: date.getDate()
        }
      }
    });
  }

My form name i s form and formControlName is bookingdates,


I am getting bellow error


EditProductComponent_Host.html:1 ERROR Error: Must supply a value for form control with name: 'product_name'.

**Comment by kekeh** [comment]
Probably you have also other controls in the form group? If so and you want to set value only to the bookingdates control then replace setValue with patchValue call.

**Comment by ketanbgm** [comment]
Thank you very much, it worked for me.
