### ISSUE TITLE
Set maximium number of days that can be selected by user

### ISSUE THREAD

**Issue by KowsalyaPK** [kekeh/mydaterangepicker#80]
It would be nice to have an option in which if we specify the maximum number of days in number like 30 or 60, then the user can select only 30 days or 60 days respectively

**Comment by kekeh** [comment]
This can be partially done by using **disableUntil** and **disableSince** options. For example setting:
```javascript
disableUntil: {year: 2017, month: 10, day: 1};
disableSince: {year: 2017, month: 10, day: 31};
```
Now you can only select ranges between 02.10.2017 - 30.10.2017
