### ISSUE TITLE
Problem with updating to angular 4

### ISSUE THREAD

**Issue by imleihuang** [kekeh/mydaterangepicker#82]
Hi,

I have updated my project from angular 2 to angular 4, but it has problem with mydaterangepicker.

the problem looks jest like this: 

 ERROR in ./node_modules/mydaterangepicker/bundles/mydaterangepicker.umd.js
Module not found : error : Can't resolve './services/my-date-range-picker.date.range.util.service' in 'C:\VSTS\*****\WebApp\node_modules\mydaterangepicker\bundles' [C:\VSTS\*****\WebApp\FuelHubWeb.c
sproj]
       @ ./node_modules/mydaterangepicker/bundles/mydaterangepicker.umd.js 10:9-75
       @ ./ClientApp/src/modules/feature/seller/seller.module.ts
       @ ./ClientApp/src/modules/core/core-app/app-routing.module.ts
       @ ./ClientApp/src/modules/core/core-app/app.module.ts
       @ ./ClientApp/boot-server.ts

any idea? 

Best Regards,

Leon

**Comment by kekeh** [comment]
Try to update version 4.1.11. Probably it fix the error.
