### ISSUE TITLE
Set model with beginJsDate and endJsDate

### ISSUE THREAD

**Issue by windmaomao** [kekeh/mydaterangepicker#88]
please let me know if the model value can be set using combo `beginJsDate` and `endJsDate`, thanks. 

```
    if (Array.isArray(vals) && vals.length) {
      const beginDate = this.parsePipe.transform(vals[0], this.opts.dateFormat);
      const endDate = this.parsePipe.transform(vals[1], this.opts.dateFormat);
      this.dates = { beginJsDate: beginDate.toDate(), endJsDate: endDate.toDate() };
    } else {
      this.dates = null;
    }
```

with HTML 

```
       <my-date-range-picker name="myRangeDates" 
         [options]="opts" [ngModel]="dates" (ngModelChange)="onModelChange($event)" (dateRangeChanged)="onDateRangeChanged($event)"
        ></my-date-range-picker>

```

I tried to set it, but the range doesn't seem to be displayed afterward.

**Comment by kekeh** [comment]
Javascript date format is not supported. It must be in the [IMyDate](https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/interfaces/my-date.interface.ts) format like here: https://github.com/kekeh/mydaterangepicker#1-ngmodel-binding
