### ISSUE TITLE
I want to use '-' as an option.

### ISSUE THREAD

**Issue by hanwoo** [kekeh/mydaterangepicker#92]
MyDateRangePicker.prototype.writeValue
->this.selectionDayTxt = begin +  **" - "** + end;
'2017-11-16 - 2017-11-22' than
'2017-11-16 ~ 2017-11-22' This is better.
So, I want to change '-' to '~'.
Is it possible?

**Comment by kekeh** [comment]
It is not configurable. It requires code changes.

You can create own version of the component. You can start from here: https://github.com/kekeh/mydaterangepicker#development-of-this-component
