### ISSUE TITLE
Is there any way to get the month or year selectors out of the component?

### ISSUE THREAD

**Issue by Zerokk** [kekeh/mydaterangepicker#94]
Hi there!

First, thanks for this awesome component. I'm now using it in a project, but as I didn't really like the month selector, I wanted to put two buttons at the sides of the component, so they work as "Previous month" and "Next month", but I'm not sure on how to do this, since this would be just to navigate through the monhts without changing the user's selection.

How could this be done?

Thank you!

**Comment by kekeh** [comment]
This is not possible. If you want only two buttons then code changes are needed. I don't have any plan to do so.

But you can set the **monthSelector** and the **yearSelector** option to **false**. Then the month and year selector are not opened.
