### ISSUE TITLE
Set dates from service 

### ISSUE THREAD

**Issue by almothafar** [kekeh/mydaterangepicker#96]
I'm trying to set date from service so I can see already selected date when I visit back the page, what I'm trying to do now something like:

```
@ViewChild('myDateRangePicker') myDateRangePicker: MyDateRangePicker;
public updateFilters() {
      const dateFrom = new Date(this.filterBy.dateFrom);
      const dateTo = new Date(this.filterBy.dateTo);
      this.myDateRangePicker.selectBeginDate({year: dateFrom.getFullYear(), month: dateFrom.getMonth(), day: dateFrom.getDate()});
      this.myDateRangePicker.selectEndDate({year: dateTo.getFullYear(), month: dateTo.getMonth(), day: dateTo.getDate()});
}
```

On HTML:

```
<my-date-range-picker [options]="myDateRangePickerOptions" (dateRangeChanged)="onDateRangeChanged($event)" type="text" #myDateRangePicker>
```

But this does not work, any suggestion about this issue to fix? or it is a feature to add?

**Comment by kekeh** [comment]
You can use ngModel binding to set date range.

Here is example: https://github.com/kekeh/mydaterangepicker#1-ngmodel-binding

You can also set value of model also dynamically. In the example the value is set statically.

**Comment by almothafar** [comment]
@kekeh my bad, i really missed somehow, thanks a lot :)
