### ISSUE TITLE
value is not removed if enter the text 

### ISSUE THREAD

**Issue by Mean563** [kekeh/mydaterangepicker#97]
Hi @kekeh , I was facing issue for range date picker. I was doing  same thing like below code :+1: 

```
 e.prototype.onInputFieldChanged = function(e) {
                console.log("onInputFieldChanged(): Value: ", e.value, " - dateFormat: ", e.dateFormat, " - valid: ", e.valid)
            }
         
```

But if suppose I am trying below example:

`I was trying to enter "AAAAAAAAAA"`
Event is not firing for last removed value, i was checked in `console.log()`

**Comment by kekeh** [comment]
I did one fix. Now the **inputFieldChanged** event is fired also when removing the last character from the input box.

New version of the component is: 4.2.0

You can try it here: https://kekeh.github.io/mydaterangepicker/

open console of the browser to see callback messages.
