### ISSUE TITLE
Unable to select date from January month of 2018, it shows up to only 2017 Dec 31

### ISSUE THREAD

**Issue by sandip0018** [kekeh/mydaterangepicker#99]
We are unable to select date from january 2018, it is enable up to 31 dec 2017.

`

    private _startDate      = moment().set({'year': 2017, 'month': 5, 'date': 30}).utc().startOf('day'); 
    private _endDate        = moment().utc().startOf('day').subtract(1, 'days');
    private _defaultDate    = moment().utc().startOf('day').subtract(2, 'days');
  
    private _dateRangeOptions: any = {
        
        dateFormat: 'mmm dd, yyyy',
        disableUntil: {
            year    : this._startDate.format('YYYY'), 
            month   : this._startDate.format('M'), 
            day     : this._startDate.format('D')
        },
        disableSince: {
            year    : this._endDate.format('YYYY'), 
            month   : this._endDate.format('M'), 
            day     : this._endDate.format('D')
        },
        showClearBtn: false,
        showApplyBtn: false,
        showClearDateRangeBtn: false,
        editableDateRangeField: false
    };

    /**
     * Selected date range
     * default value: _defaultDate
     */
    private _selectedRange: Object = {

        beginDate: {
            year    : this._defaultDate.format('YYYY'), 
            month   : this._defaultDate.format('M'), 
            day     : this._defaultDate.format('D')
        },
        endDate: {
            year    : this._defaultDate.format('YYYY'), 
            month   : this._defaultDate.format('M'), 
            day     : this._defaultDate.format('D')
        }
    };
`
Please find attached screenshot of result of above code.

![daterange](https://user-images.githubusercontent.com/7183797/34667308-84732ef2-f436-11e7-9ff5-50baf3a9cb1b.PNG)

can you please provide some solution for this, i think it issue in internal lib?

Thanks,
Sandip

**Comment by kekeh** [comment]
What is the type of value returned by **format** function of **moment**?

If it is a string type you have convert it to **number** before pass it to date range picker. For example:
```javascript
    disableUntil: {
        year    : Number(this._startDate.format('YYYY')), 
        month   : Number(this._startDate.format('M')), 
        day     : Number(this._startDate.format('D'))
    },
    disableSince: {
        year    : Number(this._endDate.format('YYYY')), 
        month   : Number(this._endDate.format('M')), 
        day     : Number(this._endDate.format('D'))
    },

// and

private _selectedRange: Object = {

    beginDate: {
        year    : Number(this._defaultDate.format('YYYY')), 
        month   : Number(this._defaultDate.format('M')), 
        day     : Number(this._defaultDate.format('D'))
    },
    endDate: {
        year    : Number(this._defaultDate.format('YYYY')), 
        month   : Number(this._defaultDate.format('M')), 
        day     : Number(this._defaultDate.format('D'))
    }
};
```

Does this solve your issue?

**Comment by sandip0018** [comment]
Thanks @kekeh  for providing solution, its working fine now with converting to Number.
